name: lzma
version: 0.4.0+1
author: Juan Mellado <jcmellado@gmail.com>
homepage: https://github.com/jcmellado/dart-lzma
description: LZMA compression library.

environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  fixnum: ">=0.9.0 <0.11.0"
  
dev_dependencies:
  test: ^0.12.0
